### ISSUE TITLE
Broke my computer!

### ISSUE THREAD

**Issue by DASPELLER4** [JakeT23cool/infiniteTATtime#1]
I opened the script, pressed the power button on my computer, and my pc turned off!!!

How dare you make malware !!!

**Comment by JakeT23cool** [comment]
This is a core feature of the program.

**Comment by DASPELLER4** [comment]
WHY U NO SAY THIS, I WILL CALL THE CYBER POLICE

**Comment by JakeT23cool** [comment]
do it

**Comment by DASPELLER4** [comment]
*ring ring*
